## Data Understanding
* Dataset structure
* Identify variables
* Classify each column

In [1]:
## import imp libraries 
import numpy as np  ## numerical computations
import pandas as pd ## data manipulation and analysis

import seaborn as sns  ## statistical visualizations
import matplotlib.pyplot as plt  ## basic visualizations

In [5]:
df = pd.read_csv(
    "../data/DiwaliSales.csv",
    encoding="unicode_escape"
)

print(df)

       User_ID    Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
0      1002903    Sanskriti  P00125942      F     26-35   28               0
1      1000732       Kartik  P00110942      F     26-35   35               1
2      1001990        Bindu  P00118542      F     26-35   35               1
3      1001425       Sudevi  P00237842      M      0-17   16               0
4      1000588         Joni  P00057942      M     26-35   28               1
...        ...          ...        ...    ...       ...  ...             ...
11246  1000695      Manning  P00296942      M     18-25   19               1
11247  1004089  Reichenbach  P00171342      M     26-35   33               0
11248  1001209        Oshin  P00201342      F     36-45   40               0
11249  1004023       Noonan  P00059442      M     36-45   37               0
11250  1002744      Brumley  P00281742      F     18-25   19               0

                State      Zone       Occupation Product_Category  Orders  \
0         Maharashtra   Western       Healthcare             Auto       1
1      Andhra Pradesh  Southern             Govt             Auto       3
2       Uttar Pradesh   Central       Automobile             Auto       3
3           Karnataka  Southern     Construction             Auto       2
4             Gujarat   Western  Food Processing             Auto       2
...               ...       ...              ...              ...     ...
11246     Maharashtra   Western         Chemical           Office       4
11247         Haryana  Northern       Healthcare       Veterinary       3
11248  Madhya Pradesh   Central          Textile           Office       4
11249       Karnataka  Southern      Agriculture           Office       3
11250     Maharashtra   Western       Healthcare           Office       3

        Amount  Status  unnamed1
0      23952.0     NaN       NaN
1      23934.0     NaN       NaN
2      23924.0     NaN       NaN
3      23912.0     NaN       NaN
4      23877.0     NaN       NaN
...        ...     ...       ...
11246    370.0     NaN       NaN
11247    367.0     NaN       NaN
11248    213.0     NaN       NaN
11249    206.0     NaN       NaN
11250    188.0     NaN       NaN

[11251 rows x 15 columns]

In [6]:
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

    Before analyzing any dataset, answer these questions:

    How many rows and columns are present?
    What do the first few records look like?
    What do the last few records look like?
    Are the records consistent?
    Can we inspect random samples?

In [ ]:
## Dataset shape : returns number of rows and columns
df = pd.read_csv(
    "../data/DiwaliSales.csv",
    encoding="unicode_escape"
)

print(df.shape) 

## Records : 11,251
## Columns : 15

(11251, 15)

In [ ]:
## First Five Records (verify cols, understand values, check data laoding)

df.head()

## Observation : 1 row reprsenents a complete transaction of an order being placed , it also tells us customers demographic information , purchase records , overall sales and geogrpahical information.

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

In [14]:
df.tail()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370.0,NaN,NaN
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367.0,NaN,NaN
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213.0,NaN,NaN
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206.0,NaN,NaN
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188.0,NaN,NaN

In [ ]:
# Random sample : displays random observations 
# unlike head and tail anomalies that may occur in the middle of the dataset.

df.sample(5)

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
6301,1004322,Jason,P0095442,M,51-55,54,1,Delhi,Central,Aviation,Electronics & Gadgets,4,7874.0,NaN,NaN
11159,1002583,Ruben,P00120342,F,36-45,36,0,Delhi,Central,Healthcare,Office,2,768.0,NaN,NaN
6083,1005098,Saloni,P00282242,F,51-55,51,0,Uttarakhand,Central,Hospitality,Electronics & Gadgets,1,7955.0,NaN,NaN
6616,1003489,Phillip,P00184942,F,18-25,21,1,Haryana,Northern,Chemical,Food,2,7754.0,NaN,NaN
3120,1005522,Mitch,P00299242,F,26-35,34,0,Madhya Pradesh,Central,Textile,Food,1,12090.0,NaN,NaN

In [16]:
df.sample(10, random_state=42)

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
5749,1006036,Halladay,P00115242,M,26-35,30,0,Haryana,Northern,Banking,Electronics & Gadgets,4,8072.0,NaN,NaN
7335,1003110,Sara,P00288942,F,26-35,31,0,Uttar Pradesh,Central,Retail,Clothing & Apparel,2,6981.0,NaN,NaN
5932,1002167,Gannaway,P00187342,M,26-35,28,1,Uttarakhand,Central,Automobile,Electronics & Gadgets,3,8008.0,NaN,NaN
3819,1002083,Mohan,P00216342,F,18-25,22,0,Karnataka,Southern,Chemical,Food,2,11378.0,NaN,NaN
6395,1003387,Amol,P00216842,F,18-25,22,0,Rajasthan,Northern,Food Processing,Electronics & Gadgets,4,7843.0,NaN,NaN
8084,1002656,Valerie,P00057442,F,55+,61,0,Kerala,Southern,Banking,Electronics & Gadgets,4,5978.0,NaN,NaN
1068,1005761,Kartikay,P00223242,F,26-35,33,0,Delhi,Central,Automobile,Footwear & Shoes,4,16865.0,NaN,NaN
4881,1000513,Rachel,P00302042,F,26-35,31,0,Himachal Pradesh,Northern,Banking,Clothing & Apparel,3,8807.0,NaN,NaN
668,1004663,Manshul,P00220342,M,26-35,30,1,Uttar Pradesh,Central,IT Sector,Food,3,19380.0,NaN,NaN
6554,1005520,Farry,P00178042,F,46-50,46,0,Jharkhand,Eastern,Healthcare,Electronics & Gadgets,2,7779.0,NaN,NaN

Each row represents a single customer transaction and contains information related to Customer, Product, Sales, and Geographical dimensions, making it suitable for end-to-end business analysis.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB

The dataset contains 15 columns consisting of integer, floating-point, and object data types. Most columns are complete, while Amount contains missing values and Status and unnamed1 contain only NULL values. The dataset occupies approximately 1.3 MB of memory.

In [ ]:
## Column names 

df.columns
## The dataset contains columns representing customer information, product information, sales metrics, and geographical information.

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount', 'Status', 'unnamed1'],
      dtype='object')

In [ ]:
df.info()

# Dataset contains 15 columns.
# Integer, float and object data types are present.
# Amount contains missing values.
# Status and unnamed1 contain only NULL values.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB

In [ ]:
df.describe()
# Average customer age ≈ 35 years.
# Average purchase amount ≈ ₹9,454.
# Average order quantity ≈ 2.
# Age ranges between 12–92 years.

,User_ID,Age,Marital_Status,Orders,Amount,Status,unnamed1
count,1.125100e+04,11251.000000,11251.000000,11251.000000,11239.000000,0.0,0.0
mean,1.003004e+06,35.421207,0.420318,2.489290,9453.610858,NaN,NaN
std,1.716125e+03,12.754122,0.493632,1.115047,5222.355869,NaN,NaN
min,1.000001e+06,12.000000,0.000000,1.000000,188.000000,NaN,NaN
25%,1.001492e+06,27.000000,0.000000,1.500000,5443.000000,NaN,NaN
50%,1.003065e+06,33.000000,0.000000,2.000000,8109.000000,NaN,NaN
75%,1.004430e+06,43.000000,1.000000,3.000000,12675.000000,NaN,NaN
max,1.006040e+06,92.000000,1.000000,4.000000,23952.000000,NaN,NaN

#############################################################################################

# Data Cleaning

#### MISSING VALUES

In [27]:
## Let us inspect MISSING VALUES

df.isnull().sum()

User_ID                 0
Cust_name               0
Product_ID              0
Gender                  0
Age Group               0
Age                     0
Marital_Status          0
State                   0
Zone                    0
Occupation              0
Product_Category        0
Orders                  0
Amount                 12
Status              11251
unnamed1            11251
dtype: int64

* Amount contains 12 missing values 
* Status and unnamed 1 contain only null 
* Remaining columns contain no missing values.

In [30]:
## Duplicates 

df.duplicated().sum()

8

In [31]:
df.dtypes

User_ID               int64
Cust_name            object
Product_ID           object
Gender               object
Age Group            object
Age                   int64
Marital_Status        int64
State                object
Zone                 object
Occupation           object
Product_Category     object
Orders                int64
Amount              float64
Status              float64
unnamed1            float64
dtype: object

In [ ]:
## Invalid Values

df[['Age', 'Orders', 'Amount']].describe()


## Observation
# Age ranges between 12–92.
# Orders range between 1–4.
# Purchase amount ranges between ₹188–₹23,952.
# No immediately suspicious numerical values were observed.

                Age        Orders        Amount
count  11251.000000  11251.000000  11239.000000
mean      35.421207      2.489290   9453.610858
std       12.754122      1.115047   5222.355869
min       12.000000      1.000000    188.000000
25%       27.000000      1.500000   5443.000000
50%       33.000000      2.000000   8109.000000
75%       43.000000      3.000000  12675.000000
max       92.000000      4.000000  23952.000000

##### Remove Unecessary Columns

In [ ]:
# The Status and unnamed1 columns contain only missing values and do not contribute to the analysis.

df.drop(
    columns = ["Status","unnamed1"], inplace = True
)