In [3]:
import pandas as pd 

df = pd.read_csv("../data/DiwaliSales.csv", encoding = "unicode_escape")

dirty_df = df.copy()

In [4]:
# mising values 

df.isnull().sum()

User_ID                 0
Cust_name               0
Product_ID              0
Gender                  0
Age Group               0
Age                     0
Marital_Status          0
State                   0
Zone                    0
Occupation              0
Product_Category        0
Orders                  0
Amount                 12
Status              11251
unnamed1            11251
dtype: int64

* Amount = 12
* Status = all nulls
* unnamed = all nulls

In [5]:
## removing nulls cols 

dirty_df.drop(columns = ["Status"], inplace = True)

dirty_df.drop(["unnamed1"], axis = 1, inplace = True)

In [6]:
dirty_df.isnull().sum()

User_ID              0
Cust_name            0
Product_ID           0
Gender               0
Age Group            0
Age                  0
Marital_Status       0
State                0
Zone                 0
Occupation           0
Product_Category     0
Orders               0
Amount              12
dtype: int64

In [11]:
dirty_df.drop([0], axis=0, inplace = True)

In [14]:
dirty_df.drop([1,2], axis=0, inplace = True)

## dropna only removes values with nan 
    ommon Parameters
    Code	Meaning
    df.dropna()	Remove rows with NaN.
    df.dropna(axis=1)	Remove columns with NaN.
    df.dropna(inplace=True)	Modify the original DataFrame.
    df.dropna(subset=["Amount"])	Remove only rows where Amount is NaN.


    Function	Purpose
    drop(columns=["Status"])	Remove specific column(s) you choose.
    dropna(axis=1)	Remove every column that contains at least one NaN (or all NaN, depending on parameters).


    drop() → I decide what to remove.
    dropna() → Pandas decides based on missing values. 


    Rule of Thumb
    Known rows? → drop(index=...)
    Known columns? → drop(columns=...)
    Rows with NULLs? → dropna()
    Replace NULLs? → fillna()

In [19]:
## fillna() : replacess missing values

dirty_df["Amount"] = dirty_df['Amount'].fillna(0)

dirty_df['Amount'].isnull().sum()

dirty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11248 entries, 3 to 11250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11248 non-null  int64
 1   Cust_name         11248 non-null  object
 2   Product_ID        11248 non-null  object
 3   Gender            11248 non-null  object
 4   Age Group         11248 non-null  object
 5   Age               11248 non-null  int64
 6   Marital_Status    11248 non-null  int64
 7   State             11248 non-null  object
 8   Zone              11248 non-null  object
 9   Occupation        11248 non-null  object
 10  Product_Category  11248 non-null  object
 11  Orders            11248 non-null  int64
 12  Amount            11248 non-null  float64
dtypes: float64(1), int64(4), object(8)
memory usage: 1.1+ MB

In [ ]:
## Fill with mean 

dirty_df['Amount'] = dirty_df['Amount'].fillna(dirty_df['Amount'].mean())

dirty_df['Amount']

In [21]:
dirty_df['Amount']

3        23912.0
4        23877.0
5        23877.0
6        23841.0
7            0.0
          ...
11246      370.0
11247      367.0
11248      213.0
11249      206.0
11250      188.0
Name: Amount, Length: 11248, dtype: float64

In [22]:
# Rows where Amount is NULL
null_idx = practice_df[practice_df["Amount"].isnull()].index

# Fill with mean
practice_df["Amount"] = practice_df["Amount"].fillna(
    practice_df["Amount"].mean()
)

# Show only the rows that were filled
practice_df.loc[null_idx, ["Amount"]]

practice_df.loc[null_idx]

NameError: name 'practice_df' is not defined

In [23]:
dirty_df['Amount'] = dirty_df['Amount'].fillna(dirty_df['Amount'].median())

# Duplicates

In [ ]:
dirty_df.duplicated().sum()

# Returns the number of duplicate rows.

##view duplicate rows

8

In [25]:
dirty_df[dirty_df.duplicated()]

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount
19,1001883,Praneet,P00029842,M,51-55,54,1,Uttar Pradesh,Central,Hospitality,Auto,1,23568.0
4404,1004725,Jackson,P00150842,F,36-45,37,1,Maharashtra,Western,Hospitality,Electronics & Gadgets,4,9859.0
5703,1003208,Bowman,P00171642,F,26-35,31,0,Bihar,Eastern,Agriculture,Electronics & Gadgets,4,8088.0
5908,1001260,Dheeraj,P00344042,M,26-35,28,0,Maharashtra,Western,IT Sector,Electronics & Gadgets,4,8015.0
6173,1001325,Reese,P00111742,F,26-35,27,1,Gujarat,Western,Construction,Electronics & Gadgets,3,7923.0
8651,1000083,Gute,P00242842,M,26-35,35,0,Uttar Pradesh,Central,Hospitality,Clothing & Apparel,3,5345.0
8941,1001476,Anudeep,P00036842,M,18-25,25,0,Maharashtra,Western,IT Sector,Clothing & Apparel,4,5202.0
10571,1004404,Rittenbach,P00150142,F,26-35,28,1,Haryana,Northern,Aviation,Electronics & Gadgets,3,2304.0

In [30]:
## remove duplicate rows 

# dirty_df.drop_duplicates(inplace = True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB

In [ ]:
df.drop_duplicates(subset=["User_ID"], inplace=True)

    df["User_ID"].duplicated().sum()

In [32]:
df[df["User_ID"].duplicated(keep=True)]

ValueError: keep must be either "first", "last" or False

In [33]:
df["User_ID"].nunique()

3755

In [34]:
len(df)

11251

    Duplicates — Summary
    1. Count Duplicate Rows
    df.duplicated().sum()

    Counts duplicate rows.

    2. Show Duplicate Rows
    df[df.duplicated()]

    Shows only the duplicate copies (keeps the first occurrence).

    3. Show All Rows Involved ⭐
    df[df.duplicated(keep=False)]

    Shows both the original and duplicate rows.

    4. Remove Duplicate Rows
    df.drop_duplicates(inplace=True)

    Removes duplicate rows.

    5. Check Duplicates in a Specific Column
    df["User_ID"].duplicated().sum()

    Counts duplicate values in User_ID.

    6. Show Duplicate Values of a Column
    df[df["User_ID"].duplicated(keep=False)]

    Shows all rows where User_ID is duplicated.

    7. Remove Duplicates Based on a Column
    df.drop_duplicates(subset=["User_ID"], inplace=True)

    Keeps only one row per User_ID.

    ⚠️ Use only if duplicates in that column are errors (e.g., Employee_ID). Do not use it if repeated values are expected (e.g., customers making multiple purchases).

    Rule of Thumb
    duplicated() → Find duplicates.
    duplicated(keep=False) → Investigate duplicates.
    drop_duplicates() → Remove duplicates.
    subset=[...] → Check/remove duplicates using specific column(s).

## Validating Data types

    Check Data Types
    Check Data Type of One Column

    Convert Data Type
    Convert to Float
    onvert Back

    df["Age"] = df["Age"].astype(str)

In [38]:
dirty_df

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0
5,1000588,Joni,P00057942,M,26-35,28,1,Himachal Pradesh,Northern,Food Processing,Auto,1,23877.0
6,1001132,Balk,P00018042,F,18-25,25,1,Uttar Pradesh,Central,Lawyer,Auto,4,23841.0
7,1002092,Shivangi,P00273442,F,55+,61,0,Maharashtra,Western,IT Sector,Auto,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370.0
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367.0
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213.0
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206.0
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188.0

In [48]:
# Practice
# Task 1


dirty_df.dtypes

# Convert Orders → float

# dirty_df['Orders'] = dirty_df['Orders'].astype(float)

# Task 2

# Convert Orders → int

# dirty_df['Orders'] = dirty_df['Orders'].astype(int)

# Task 3

# Convert Age → str

#dirty_df['Age'] = dirty_df['Age'].astype(str)

# Task 4

# Convert Age → int

#dirty_df['Age'] = dirty_df['Age'].astype(int)

# Task 5

# Convert Amount → float

#dirty_df['Amount'] = dirty_df['Amount'].astype(float)

# Task 6

# Convert Amount → int

User_ID               int64
Cust_name            object
Product_ID           object
Gender               object
Age Group            object
Age                   int32
Marital_Status        int64
State                object
Zone                 object
Occupation           object
Product_Category     object
Orders                int32
Amount              float64
dtype: object

# Column operations

        df.rename(columns={"Age Group": "Age_Group"}, inplace=True)

        Rename Multiple Columns
        df.rename(
        columns={
            "Age Group": "Age_Group",
            "Marital_Status": "Marital Status"
        },
        inplace=True
    )

    . Add a New Column

    df["Discount"] = 10


    Create a Column from Existing Columns

    df["Total"] = df["Amount"] * df["Orders"]

    Delete a Column

    df["Amount"]

    Select Multiple Columns

    df[["Gender", "State", "Amount"]]

    Reorder cols 

    df = df[
        [
            "User_ID",
            "Gender",
            "Age",
            "Amount",
            "Orders"
        ]
    ]



    Rule of Thumb
    columns → View columns
    rename() → Rename columns
    [] → Select columns
    del / drop() → Delete columns
    df["new"] = ... → Create new columns

In [69]:
# # Task 1

# # Rename Age Group → Age_Group

# #dirty_df.rename(columns={"Age Group" : "Age_Group"}, inplace = True)

# # Task 2

# # Rename Marital_Status → Marital Status

# dirty_df.rename(
#     columns = {
#         "Marital_Status" : "Marital Status",
#         "Orders" : "Orders_Qty"
#     }, inplace = True
# )



# # Task 3

# # Create a column named Total = Amount × Orders
# dirty_df['Total Revenue'] = dirty_df['Amount']*dirty_df['Orders_Qty']

# # Task 4

# # Create a column named Discount = 5

# dirty_df['Discount'] = 5

# # Task 5

# # Delete Discount

# dirty_df.drop(columns = ['Discount'], inplace = True)

# # Task 6

# # Display only Gender, State, and Amount

dirty_df[['Gender','State','Amount']]

# # Task 7

# # Display all column names

dirty_df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders_Qty', 'Amount', 'Total Revenue'],
      dtype='object')

In [62]:
dirty_df

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital Status,State,Zone,Occupation,Product_Category,Orders_Qty,Amount,Total Revenue,Discount
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,47824.0,5
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,47754.0,5
5,1000588,Joni,P00057942,M,26-35,28,1,Himachal Pradesh,Northern,Food Processing,Auto,1,23877.0,23877.0,5
6,1001132,Balk,P00018042,F,18-25,25,1,Uttar Pradesh,Central,Lawyer,Auto,4,23841.0,95364.0,5
7,1002092,Shivangi,P00273442,F,55+,61,0,Maharashtra,Western,IT Sector,Auto,1,0.0,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370.0,1480.0,5
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367.0,1101.0,5
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213.0,852.0,5
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206.0,618.0,5
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188.0,564.0,5

    # Value validation
    Unique Values

    Returns all distinct values in a column.

    df["Gender"].unique()

    Output:

    ['F' 'M']
    2. Count Unique Values

    Counts the number of distinct values.

    df["State"].nunique()

    Output:

    16
    3. Frequency Count

    Counts how many times each value appears.

    df["Gender"].value_counts()

    Output:

    F    7832
    M    3407
    Sort by Frequency
    df["Occupation"].value_counts()

    or

    df["Occupation"].value_counts(ascending=True)
    Practice
    Task 1



    Rule of Thumb
    unique() → Show unique values.
    nunique() → Count unique values.
    value_counts() → Count frequency of each value.

In [77]:
# Display all unique occupations.

# Task 2

# Count the number of unique states.

dirty_df['State'].nunique()
dirty_df['State'].unique()

#print(f"Gender : {dirty_df['Gender'].unique()}")

# Task 3

# Display the frequency of each product category.

dirty_df['Product_Category'].value_counts(ascending = True)

# Task 4

# Display the frequency of each age group.

dirty_df['Age Group'].value_counts(ascending = True)

Age Group
0-17      296
55+       428
51-55     831
46-50     987
18-25    1878
36-45    2285
26-35    4535
Name: count, dtype: int64